# Generated by Django 5.0.6 on 2026-10-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resume', '0003_add_certifications_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_status', models.CharField(choices=[('processing', 'Processing'), ('evaluated', 'Evaluated'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('decision_status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='new', max_length=20)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('skill_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('education_score', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_evaluations', to='resume.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_evaluations', to='jobs.job')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidateevaluation',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_evaluation'),
        ),
    ]
