# Generated by Django 5.0.6 on 2026-06-12 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('required_skills', models.JSONField(default=list)),
                ('optional_skills', models.JSONField(default=list)),
                ('min_experience', models.IntegerField(default=0)),
                ('education_level', models.CharField(choices=[('Matric', 'Matric'), ('Intermediate', 'Intermediate'), ('BSc / BE', 'BSc / BE'), ('MSc / MS', 'MSc / MS'), ('PhD', 'PhD')], default='BSc / BE', max_length=20)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('skill_weight', models.FloatField(default=0.5)),
                ('experience_weight', models.FloatField(default=0.3)),
                ('education_weight', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
