# Generated by Django 5.0.6 on 2026-06-12 11:09

import django.db.models.deletion
import fairhire.apps.resume.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to=fairhire.apps.resume.models.resume_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('education', models.TextField(blank=True)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('experience_years', models.FloatField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('work_history', models.JSONField(default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('skill_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('education_score', models.FloatField(blank=True, null=True)),
                ('missing_skills', models.JSONField(default=list)),
                ('score_explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('hr_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
